[loadbalancer]
lb01 ansible_host=54.254.121.125

[apache]
web01 ansible_host=10.0.2.94

[nginx]
web02 ansible_host=10.0.3.24

[webservers:children]
apache
nginx

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_python_interpreter=/usr/bin/python3

[webservers:vars]
ansible_ssh_common_args='-o ProxyJump=ubuntu@54.254.121.125'
